
apiVersion: v1
kind: Service
metadata:
  name: kube-flask-service
spec:
  type: NodePort
  selector:
    app: kube-flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
